### ISSUE TITLE
Target "Qt6::Widgets" was not found. 请问这个问题如何解决？

### ISSUE THREAD

**Issue by newforrestgump001** [alex-hjm/pcl-api#2]
Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.17763.
Could NOT find Qt6WidgetsTools (missing: Qt6WidgetsTools_DIR)
CMake Warning at D:/Qt/6.2.3/mingw_64/lib/cmake/Qt6/Qt6Config.cmake:177 (find_package):
  Found package configuration file:

    D:/Qt/6.2.3/mingw_64/lib/cmake/Qt6Widgets/Qt6WidgetsConfig.cmake

  but it set Qt6Widgets_FOUND to FALSE so package "Qt6Widgets" is considered
  to be NOT FOUND.  Reason given by package:

  Target "Qt6::Widgets" was not found.

Call Stack (most recent call first):
  CMakeLists.txt:27 (find_package)

CMake Error at CMakeLists.txt:27 (find_package):
  Found package configuration file:

    D:/Qt/6.2.3/mingw_64/lib/cmake/Qt6/Qt6Config.cmake

  but it set Qt6_FOUND to FALSE so package "Qt6" is considered to be NOT
  FOUND.  Reason given by package:

  Failed to find Qt component "Widgets".

  Expected Config file at
  "D:/Qt/6.2.3/mingw_64/lib/cmake/Qt6Widgets/Qt6WidgetsConfig.cmake" exists

  

Configuring incomplete, errors occurred!
See also "D:/opensource/pcl-api-master/build5/CMakeFiles/CMakeOutput.log".
See also "D:/opensource/pcl-api-master/build5/CMakeFiles/CMakeError.log".

**Comment by alex-hjm** [comment]
cmakelists add:
set(CMAKE_PREFIX_PATH "D:/Qt/5.15.2/msvc2019_64")
set(CMAKE_PROJECT_INCLUDE_BEFORE D:/Qt/Tools/QtCreator/share/qtcreator/package-manager/auto-setup.cmake)
set(Qt5Core_DIR D:/Qt/5.15.2/msvc2019_64/lib/cmake/Qt5Core)
set(Qt5Gui_DIR D:/Qt/5.15.2/msvc2019_64/lib/cmake/Qt5Gui)
set(Qt5Widgets_DIR D:/Qt/5.15.2/msvc2019_64/lib/cmake/Qt5Widgets)
set(Qt5_DIR D:/Qt/5.15.2/msvc2019_64/lib/cmake/Qt5)

**Comment by newforrestgump001** [comment]
Thanks a lot! I succeed to build in windows10, Have you  tested in Ubuntu?

**Comment by newforrestgump001** [comment]
I have built them after commenting several lines in ubuntu18.04，sincere thanks for you!
